[package]
name = "sandbox"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.27.0", features = ["derive"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
